#!/bin/bash
sudo tar -cvzf /var/www/vdbbackups/backup-$(date +"%Y-%m-%d").tar.gz --exclude=*.tar.gz --exclude=/var/www/vdbbackups /var/www > /v
ar/www/vdbbackups/$(date +"%Y-%m-%d").log
### MAKE SURE YOU CHANGE "secretpassword" below or remember it :)
sudo zip /var/www/vdbbackups/backup-$(date +"%Y-%m-%d").tar.gz.zip -e -P passwordhere /var/www/vdbbackups/backup-$(date +"%Y-%m-%d").t
ar.gz
sudo find /var/www/vdbbackups/ -type f -mtime +7 -execdir rm -- {} \; | sudo tee -a /var/www/vdbbackups/del.log
## CHANGE "bzackup" to a mysql user and "sqlpassword" to the password for that user
mysqldump --skip-events -u mybzackup --password=passwordhere vdb > /var/www/vdbbackups/database-$(date +"%Y-%m-%d").sql 2> /var/www/vd
bbackups/db-$(date +"%Y-%m-%d").log
### MAKE SURE YOU CHANGE "secretpassword" below or remember it :)
sudo zip /var/www/vdbbackups/database-$(date +"%Y-%m-%d").sql.zip -e -P passwordhere /var/www/vdbbackups/database-$(date +"%Y-%m-%d").
sql


# removes unprotected data
sudo rm /var/www/vdbbackups/backup-$(date +"%Y-%m-%d").tar.gz
sudo rm /var/www/vdbbackups/database-$(date +"%Y-%m-%d").sql