#!/bin/bash
sudo tar -cvzf /var/www/backups/backup-$(date +"%Y-%m-%d").tar.gz --exclude=*.tar.gz --exclude=/var/www/backups /var/www > /var/www/backups/$(date +"%Y-%m-%d").log
### MAKE SURE YOU CHANGE "secretpassword" below or remember it :)
sudo zip /var/www/backups/backup-$(date +"%Y-%m-%d").tar.gz.zip -e -P apass /var/www/backups/backup-$(date +"%Y-%m-%d").tar.gz
sudo find /var/www/backups/backup-2* -mtime +7 -exec rm -v {} \; | sudo tee -a /var/www/backups/del.log
## CHANGE "bzackup" to a mysql user and "sqlpassword" to the password for that user
mysqldump -u bzackup --password=apass --all-databases > /var/www/backups/database-$(date +"%Y-%m-%d").sql 2> /var/www/backups/db-$(date +"%Y-%m-%d").log
### MAKE SURE YOU CHANGE "secretpassword" below or remember it :)
sudo zip /var/www/backups/database-$(date +"%Y-%m-%d").sql.zip -e -P apass /var/www/backups/database-$(date +"%Y-%m-%d").sql


# removes unprotected data
sudo rm /var/www/backups/backup-$(date +"%Y-%m-%d").tar.gz
sudo rm /var/www/backups/database-$(date +"%Y-%m-%d").sql

sudo cp -r /var/www/backups/* /home/michael2collins/GDrive/vdojo/dbbackup/
cd /home/michael2collins/GDrive
sudo grive > /var/www/backups/grive.log

